"""``IBrowse``: the editorial sections of the home screen.

``created_for_you`` comes from ListenBrainz' algorithmic playlists (falling back to the
user's saved playlists), ``top_artist_radios`` from the user's all-time top artists, and
``mood_playlists`` is a fixed list of radios. Every item is a ``Playlist``: the runtime
derives ``item_type`` from the items themselves.
"""

from typing import Any, List, Tuple

from musicare_metadata_plugin_sdk import IBrowse, PaginatedResult, Playlist, Section, User

from ..listenbrainz import ListenBrainz
from ..providers import LISTENBRAINZ_SITE, MOOD_PLAYLISTS

LISTENBRAINZ_OWNER = User(
    id="listenbrainz", name="ListenBrainz", external_uri="https://listenbrainz.org"
)

_SECTIONS = (
    Section(
        id="created_for_you",
        title="Created For You",
        description="Algorithmic playlists generated by ListenBrainz based on your liked songs",
    ),
    Section(
        id="top_artist_radios",
        title="Your Top Artist Radios",
        description="Dynamic recommendation radios based on your favorite artists",
    ),
    Section(
        id="mood_playlists",
        title="Mood Playlists",
        description="Dynamic playlists generated based on listening moods",
    ),
)


class MusicBrainzBrowse(IBrowse):
    def __init__(self, lb: ListenBrainz, user: Any) -> None:
        self._lb = lb
        self._user = user

    def sections(self, offset: int = 0, limit: int = 20) -> PaginatedResult[Section]:
        return PaginatedResult(
            items=list(_SECTIONS), total=len(_SECTIONS), offset=offset, limit=limit
        )

    def section_items(
        self, id: str, offset: int = 0, limit: int = 20
    ) -> PaginatedResult[Playlist]:
        username = str(self._user.me().get("user_id") or "listenbrainz")
        total = 0
        items: List[Playlist] = []

        if id == "created_for_you":
            items = self._created_for(username)
            if not items:
                return self._user.saved_playlists(offset, limit)
        elif id == "top_artist_radios":
            items, total = self._top_artist_radios(username)
        elif id == "mood_playlists":
            items, total = self._mood_playlists()

        return PaginatedResult(
            items=items[offset : offset + limit],
            total=total if total > 0 else len(items),
            offset=offset,
            limit=limit,
        )

    def _created_for(self, username: str) -> List[Playlist]:
        items: List[Playlist] = []
        for entry in self._lb.created_for(username):
            playlist = entry.get("playlist") if isinstance(entry, dict) else None
            if not isinstance(playlist, dict):
                continue
            identifier = playlist.get("identifier")
            if not identifier:
                continue
            creator = str(playlist.get("creator") or username)
            items.append(
                Playlist(
                    id=str(identifier).rsplit("/", 1)[-1],
                    name=str(playlist.get("title") or ""),
                    description=str(playlist.get("annotation") or ""),
                    external_uri=str(identifier),
                    owner=User(
                        id=creator,
                        name=creator,
                        external_uri=f"{LISTENBRAINZ_SITE}user/{creator}",
                    ),
                    images=[],
                )
            )
        return items

    def _top_artist_radios(self, username: str) -> Tuple[List[Playlist], int]:
        stats = self._lb.stats_artists(username, 5)
        items: List[Playlist] = []
        for entry in stats:
            if not isinstance(entry, dict):
                continue
            name = str(
                entry.get("artist_name") or entry.get("artist_credit_name") or "Unknown Artist"
            )
            mbid = entry.get("artist_mbid")
            items.append(
                Playlist(
                    id=f"radio:artist:{name}",
                    name=f"{name} Radio",
                    description=f"Algorithmic recommendation radio based on {name}",
                    external_uri=f"https://listenbrainz.org/artist/{mbid}",
                    owner=LISTENBRAINZ_OWNER,
                    images=[],
                )
            )
        return items, len(stats)

    def _mood_playlists(self) -> Tuple[List[Playlist], int]:
        items = [
            Playlist(
                id=f"radio:tag:{tag}",
                name=title,
                description=f"Algorithmic recommendations generated based on the {tag} mood",
                external_uri="https://listenbrainz.org",
                owner=LISTENBRAINZ_OWNER,
                images=[],
            )
            for tag, title in MOOD_PLAYLISTS
        ]
        return items, len(items)
